import Head from 'next/head'
import styles from './index.module.scss'
import Header from './components/Header'
// import Footer from './components/Footer'
import React, { useEffect } from 'react'
import { IProps } from './type'

/*
 * 整体框架布局
 */
export default function Layout(props: IProps) {
    const { children } = props

    useEffect(() => {}, [])

    return (
        <div className={styles.container} id={'container'}>
            <Head>
                <title>小折秋</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="initial-scale=1, width=device-width" />
                <link
                    rel="icon"
                    href="https://vkceyugu.cdn.bspapp.com/VKCEYUGU-5f7e3460-38bd-45dd-848a-d56d8287d2f9/54907a64-8c8b-476e-898b-31c5b64a0313.ico"
                />
            </Head>
            <header className={styles.header}>
                <Header />
            </header>
            <div className={styles.showContainer} id={'showContainer'}>
                <main className={styles.main}>{children}</main>
                {/*<Footer />*/}
            </div>
        </div>
    )
}
